name: PR Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up Java 17 for running Gradle
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
